<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\EmploymentStatus;
use App\Models\Grade;
use App\Models\OrgUnit;
use App\Models\Position;
use App\Models\Site;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class EmployeeVariationSeeder extends Seeder
{
    /**
     * Demo block reserved for variation rows so re-runs stay idempotent
     * and never collide with numbers generated by the sequence.
     */
    private const NUMBER_BLOCK = 900;

    /**
     * Add the workforce variations the deterministic EmployeeSeeder does
     * not cover: recent hires on probation, contract and internship, and
     * probation end dates on every probation row. Tenure- and status-based
     * rules (benefit eligibility, probation reporting) then have both
     * passing and failing examples.
     */
    public function run(): void
    {
        $statuses = EmploymentStatus::query()->get()->keyBy('code');
        $grades = Grade::query()->get()->keyBy('name');
        $units = OrgUnit::query()->get()->keyBy('code');
        $sites = Site::query()->get()->keyBy('code');
        $positions = Position::query()->get()->keyBy('code');

        $hire = function (int $offset, string $name, string $gender, string $unitCode, string $positionCode, string $gradeName, string $statusCode, string $siteCode, Carbon $joinDate) use ($statuses, $grades, $units, $sites, $positions): Employee {
            $unit = $units->get($unitCode);
            $department = $unit?->department;
            $site = $sites->get($siteCode);

            return Employee::query()->updateOrCreate(
                ['employee_number' => sprintf('EMP-%05d', self::NUMBER_BLOCK + $offset)],
                [
                    'user_id' => null,
                    'manager_id' => $this->managerFor($department?->id, $unit?->id),
                    'name' => $name,
                    'gender' => $gender,
                    'birth_place' => $site?->city ?? 'Jakarta',
                    'birth_date' => $joinDate->copy()->subYears(24)->format('Y-m-d'),
                    'email' => strtolower(str_replace(' ', '.', $name)).'@example.test',
                    'phone' => '08'.str_pad((string) (700000 + $offset), 10, '0', STR_PAD_LEFT),
                    'identity_number' => str_pad((string) (9500000000000000 + $offset), 16, '0', STR_PAD_LEFT),
                    'address' => 'Jl. Merdeka No. '.$offset,
                    'city' => $site?->city ?? 'Jakarta',
                    'province' => $site?->province ?? 'DKI Jakarta',
                    'postal_code' => $site?->postal_code ?? '12190',
                    'emergency_contact_name' => 'Emergency Contact '.$name,
                    'emergency_contact_relationship' => 'Parent',
                    'emergency_contact_phone' => '08'.str_pad((string) (800000 + $offset), 10, '0', STR_PAD_LEFT),
                    'bank_name' => 'BCA',
                    'bank_account_number' => sprintf('8%09d', $offset),
                    'bank_account_name' => $name,
                    'division_id' => $department?->division_id,
                    'department_id' => $department?->id,
                    'org_unit_id' => $unit?->id,
                    'position_id' => $positions->get($positionCode)?->id,
                    'grade_id' => $grades->get($gradeName)?->id,
                    'site_id' => $site?->id,
                    'employment_status_id' => $statuses->get($statusCode)?->id,
                    'join_date' => $joinDate->toDateString(),
                    'end_date' => null,
                    'probation_end_date' => $statusCode === 'PROB' ? $joinDate->copy()->addMonths(3)->toDateString() : null,
                    'photo_path' => null,
                    'is_active' => true,
                ],
            );
        };

        $today = Carbon::today();

        // Two months on probation: below the 12-month tenure the education
        // benefit requires, and still inside the probation window.
        $hire(1, 'Nadia Rahmawati', 'female', 'ORG-LINE', 'POS-PRD', 'Staff', 'PROB', 'FAC-SBY', $today->copy()->subMonths(2)->startOfMonth());

        // The newest commercial hire: no benefit enrollment is possible yet.
        $hire(2, 'Bagas Setiawan', 'male', 'ORG-OUT', 'POS-SLS', 'Staff', 'PROB', 'BR-JKT', $today->copy()->subMonth()->startOfMonth());

        // Eight months on a fixed-term contract: eligible for medical, not
        // for the one-time education assistance.
        $hire(3, 'Citra Utami', 'female', 'ORG-INF', 'POS-ITS', 'Senior Staff', 'CONT', 'BLD-BDG', $today->copy()->subMonths(8)->startOfMonth());

        // Intern: excluded from the meal allowance and education benefits.
        $hire(4, 'Daffa Nugroho', 'male', 'ORG-TRN', 'POS-REC', 'Staff', 'INT', 'BLD-JKT-TOWER', $today->copy()->subWeeks(3));

        // Backfill the probation window on the deterministic probation rows.
        $probationId = $statuses->get('PROB')?->id;

        Employee::query()
            ->whereNull('probation_end_date')
            ->where('employment_status_id', $probationId)
            ->each(fn (Employee $employee) => $employee->update([
                'probation_end_date' => $employee->join_date->copy()->addMonths(3)->toDateString(),
            ]));
    }

    /**
     * The department head that owns the placement, falling back to the
     * unit head so the reporting line stays connected.
     */
    protected function managerFor(?int $departmentId, ?int $orgUnitId): ?int
    {
        if ($departmentId !== null) {
            $head = Employee::query()
                ->where('department_id', $departmentId)
                ->whereHas('position', fn ($query) => $query->where('code', 'POS-DEP-HEAD'))
                ->value('id');

            if ($head !== null) {
                return (int) $head;
            }
        }

        if ($orgUnitId !== null) {
            $head = Employee::query()
                ->where('org_unit_id', $orgUnitId)
                ->whereHas('position', fn ($query) => $query->where('code', 'POS-UNIT-HEAD'))
                ->value('id');

            if ($head !== null) {
                return (int) $head;
            }
        }

        return null;
    }
}
